### ISSUE TITLE
Klassenname

### ISSUE THREAD

**Issue by henobi** [syncgw/contao-isotope_stin#1]
Hallo,

ich habe einen kleinen Bug gefunden, der eine ClassNotFound-Exception ausgelöst hat:

Der Dateiname der Klasse IsotopeSTIN lautet IsotopeStin.php und stimmt somit nicht überein.
Die Datei müsste einfach in IsotopeSTIN.php umbenannt werden.

Vielen Dank :)

**Comment by syncgw** [comment]
Datei umbenannt. Vielen Dank für den Tipp
